// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-formulations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/data/referenceFormulations.ts
var r = (name, cat, qtyText, part) => ({
  name,
  cat,
  qty: 0,
  unit: qtyText,
  part
});
var stepsOf = (arr) => arr.map((s) => ({ step: s }));
var qcOf = (arr) => arr.map((s) => ({ parameter: s, spec: "" }));
var today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
var base = (overrides) => ({
  id: "",
  name: "",
  sanskrit: "",
  type: "",
  form: "",
  ref: "",
  use: "",
  shelf: "",
  standardBatchSize: 1,
  standardBatchUnit: "kg",
  rm: [],
  steps: [],
  qc: [],
  ipc: "",
  dosha: "",
  expectedYieldPct: 95,
  packaging: { packSizes: [], qcRetainSample: "20" },
  createdAt: today,
  isReference: true,
  ...overrides
});
var referenceFormulations = [
  base({
    id: "ref-1",
    name: "Triphala Churna",
    sanskrit: "\u0924\u094D\u0930\u093F\u092B\u0932\u093E \u091A\u0942\u0930\u094D\u0923",
    type: "Churna",
    form: "Fine powder (\u226580 mesh)",
    ref: "AFI Vol.I; API Part I",
    use: "Digestive tonic, laxative, Rasayana, eye health, detox",
    shelf: "2 years (airtight)",
    rm: [
      r("Amalaki / Amla fruit (Emblica officinalis)", "herb", "33.33%", "Dried fruit rind"),
      r("Haritaki (Terminalia chebula)", "herb", "33.33%", "Dried fruit rind"),
      r("Vibhitaki / Bibhitaki (Terminalia bellirica)", "herb", "33.33%", "Dried fruit rind")
    ],
    steps: stepsOf([
      "Raw material inspection \u2014 verify botanical identity, moisture <12%",
      "Remove seeds/kernels; retain fruit rind only",
      "Sun-dry or shade-dry rind to <8% moisture; no high-heat drying",
      "Grind each fruit separately in pulveriser",
      "Sieve through 80-mesh screen individually",
      "Weigh accurately in 1:1:1 ratio (by AFI default: Sharangdhara Samhita rule)",
      "Blend in double-cone blender or mechanical mixer until homogenous",
      "QC sample; pass organoleptic and physicochemical tests",
      "Fill in airtight HDPE containers; seal and label with batch no. + expiry"
    ]),
    qc: qcOf(["Moisture <8%", "Ash value \u226410% w/w", "pH (10% aq.) 3.5\u20135.0", "TLC fingerprint (gallic acid)", "Heavy metals <10ppm Pb", "Microbial <10\u2075 CFU/g", "Tannin content \u22653% w/w"]),
    ipc: "Particle size uniformity at each sieve step; blend uniformity check",
    dosha: "Tridoshic (all three doshas balanced)"
  }),
  base({
    id: "ref-2",
    name: "Chyawanprash Avaleha",
    sanskrit: "\u091A\u094D\u092F\u0935\u0928\u092A\u094D\u0930\u093E\u0936 \u0905\u0935\u0932\u0947\u0939",
    type: "Avaleha",
    form: "Semi-solid jam / linctus",
    ref: "Charaka Samhita Chikitsa 1/1; AFI Vol.II",
    use: "Rasayana, immunity, respiratory health, anti-aging, vitality",
    shelf: "3 years",
    rm: [
      r("Amla / Amalaki (Emblica officinalis)", "herb", "1 kg fresh (main)", "Fresh fruit"),
      r("Ashwagandha (Withania somnifera)", "herb", "As per formula", "Root"),
      r("Shatavari (Asparagus racemosus)", "herb", "As per formula", "Root tuber"),
      r("Guduchi / Giloy (Tinospora cordifolia)", "herb", "As per formula", "Stem"),
      r("Pippali / Long pepper (Piper longum)", "herb", "As per formula", "Fruit"),
      r("Sugar candy / Mishri (Sita)", "base", "~2.5 kg", "Processed sugar"),
      r("Sesame oil (Til taila)", "base", "300 g", "Cold-pressed oil"),
      r("Cow ghee (Ghrita)", "animal", "300 g", "Clarified butter"),
      r("Honey (Madhu)", "animal", "Added cold", "Bee honey \u2014 added after cooling")
    ],
    steps: stepsOf([
      "Prepare decoction (Kasaya): boil ~50 herbs in 16\xD7 water; reduce to 1/4 volume; strain",
      "Wash, peel and boil Amla fruits in the decoction until soft",
      "Remove Amla seeds; pound pulp to smooth paste",
      "Heat sesame oil and ghee together in SS vessel",
      'Fry Amla pulp in oil+ghee mixture until colour changes and fat separates \u2014 "Sneha" test',
      "Transfer fried pulp to decoction; add sugar candy and heat on low flame",
      "Stir continuously until semi-solid linctus consistency (Avaleha paka \u2014 string test)",
      "Cool to below 40\xB0C; add honey and powder spices (Prakshepa Dravyas)",
      "Mix thoroughly; fill hot in glass/HDPE jars; seal and label"
    ]),
    qc: qcOf(["Total solids \u226570% w/w", "pH 4.0\u20135.5", "Vitamin C \u22650.5 mg/g", "Moisture <20%", "Heavy metals Pb <10ppm", "Microbial <10\u2074 CFU/g"]),
    ipc: "Paka consistency (string test); temperature <40\xB0C before honey addition",
    dosha: "Tridoshic; primarily Vata-Pitta balancing"
  }),
  base({
    id: "ref-3",
    name: "Ashwagandharishta",
    sanskrit: "\u0905\u0936\u094D\u0935\u0917\u0928\u094D\u0927\u093E\u0930\u093F\u0937\u094D\u091F",
    type: "Arishta/Asava",
    form: "Fermented liquid (alcohol 5\u201310%)",
    ref: "AFI Vol.I; Bhaishajya Ratnavali",
    use: "Stress, fatigue, Vata disorders, rejuvenation, nervine tonic",
    shelf: "Indefinite",
    standardBatchUnit: "L",
    rm: [
      r("Ashwagandha (Withania somnifera)", "herb", "4.8 kg", "Root powder"),
      r("Mustak (Cyperus rotundus)", "herb", "960 g", "Rhizome"),
      r("Haritaki (Terminalia chebula)", "herb", "960 g", "Fruit"),
      r("Manjishtha (Rubia cordifolia)", "herb", "960 g", "Root"),
      r("Jaggery (Guda)", "base", "9.6 kg", "Fermentation substrate"),
      r("Dhataki Pushpa (Woodfordia fruticosa)", "process", "480 g", "Fermentation initiator"),
      r("Water", "base", "49.152 L", "Decoction medium")
    ],
    steps: stepsOf([
      "Prepare Kasaya: coarse-powder herbs, boil in 49 L water; reduce to 12 L (1/4); strain and cool",
      "Transfer decoction to fermentation vessel; fumigate vessel with Pippali churna + ghee",
      "Dissolve jaggery in warm decoction; stir to dissolve",
      "Add Dhataki Pushpa and Prakshepa Dravyas",
      "Seal vessel mouth with clay-smeared cloth in 7 layers (Sandhana)",
      "Store at 25\u201330\xB0C for 1 month",
      "Test: clear liquid, aromatic, candle test, no effervescence",
      "Filter through muslin and 5\u03BC filter",
      "Measure alcohol (5\u201310% v/v); fill in glass/HDPE bottles under nitrogen"
    ]),
    qc: qcOf(["Alcohol 5\u201310% v/v", "Total solids \u22653% w/v", "pH 3.5\u20134.5", "Clear liquid, no froth", "Microbial <10\u2074 CFU/ml", "Heavy metals within limits"]),
    ipc: "Daily fermentation monitoring: pH, temperature, smell; Candle test at 15 and 30 days",
    dosha: "Primarily Vata-balancing"
  }),
  base({
    id: "ref-4",
    name: "Sitopaladi Churna",
    sanskrit: "\u0938\u093F\u0924\u094B\u092A\u0932\u093E\u0926\u093F \u091A\u0942\u0930\u094D\u0923",
    type: "Churna",
    form: "Fine powder (\u226580 mesh)",
    ref: "Bhaishajya Ratnavali; AFI",
    use: "Cough, cold, bronchitis, fever, respiratory disorders",
    shelf: "2 years",
    rm: [
      r("Sitopala / Mishri (Sugar candy)", "base", "16 parts", "Unrefined sugar candy"),
      r("Vamsha Rochana (Bamboo silica)", "mineral", "8 parts", "Bamboo secretion"),
      r("Pippali / Long pepper (Piper longum)", "herb", "4 parts", "Fruit"),
      r("Ela / Cardamom (Elettaria cardamomum)", "herb", "2 parts", "Seed"),
      r("Twak / Dalchini (Cinnamomum verum)", "herb", "1 part", "Bark")
    ],
    steps: stepsOf([
      "Verify botanical identity and moisture (<12%) of all RM",
      "Grind Pippali, Ela, Twak separately to fine powder; pass through 80-mesh sieve",
      "Powder Vamsha Rochana; sieve",
      "Powder Sitopala separately to fine granules; sieve",
      "Weigh in correct ratio (16:8:4:2:1)",
      "Blend in double-cone blender: start with smaller quantities, gradually add larger",
      "Check blend uniformity \u2014 assay piperine content",
      "QC sample: physicochemical and microbial testing",
      "Fill in amber glass or HDPE airtight containers; insert desiccant"
    ]),
    qc: qcOf(["Moisture <8%", "Ash <5% w/w", "Piperine NLT 0.1% w/w", "TLC fingerprint match", "Heavy metals within limits", "Microbial <10\u2075 CFU/g"]),
    ipc: "Blend uniformity; particle size check; organoleptic (sweet-spicy taste)",
    dosha: "Kapha-Pitta balancing"
  }),
  base({
    id: "ref-5",
    name: "Mahanarayan Taila",
    sanskrit: "\u092E\u0939\u093E\u0928\u093E\u0930\u093E\u092F\u0923 \u0924\u0948\u0932",
    type: "Taila",
    form: "Medicated oil (Sneha Kalpana)",
    ref: "Sahasrayoga; AFI Vol.I",
    use: "Joint pain, arthritis, muscle weakness, paralysis",
    shelf: "3 years",
    standardBatchUnit: "L",
    rm: [
      r("Bilva root (Aegle marmelos)", "herb", "960 g", "Root"),
      r("Ashwagandha (Withania somnifera)", "herb", "960 g", "Root"),
      r("Bala (Sida cordifolia)", "herb", "960 g", "Root"),
      r("Shatavari (Asparagus racemosus)", "herb", "960 g", "Root tuber"),
      r("Dashamoola group (10 roots)", "herb", "960 g each", "Root"),
      r("Sesame oil (Til Taila)", "base", "9.6 L", "Cold-pressed seed oil"),
      r("Cow ghee (Ghrita)", "animal", "As per formula", "Clarified butter"),
      r("Water for decoction", "base", "98 L \u2192 24.5 L", "Decoction medium")
    ],
    steps: stepsOf([
      "Shodhana: clean and dry all herbs; reject damaged material",
      "Coarse-powder herbs; add to 98 L water; boil to 24.5 L (1/4); filter",
      "Prepare Kalka: grind designated herbs with water to fine paste",
      "Combine: sesame oil + ghee + Kalka + strained decoction",
      "Ratio: oil 1 : kalka 1/4 : liquid 4",
      "Heat on medium flame; stir continuously (Mantha)",
      "Observe Paka Lakshanas: clear froth subsides; Varti test",
      "Filter while hot through multi-layer muslin",
      "Cool, measure refractive index and specific gravity; fill in amber bottles"
    ]),
    qc: qcOf(["Refractive index 1.470\u20131.475", "Sp. gravity 0.900\u20130.910", "Acid value <5", "Saponification value 185\u2013200", "Rancidity: neg", "Heavy metals within limits"]),
    ipc: "Varti test; Madhyama Paka determination; temperature monitoring",
    dosha: "Vata-pacifying; suitable for Abhyanga and Snehapana"
  }),
  base({
    id: "ref-6",
    name: "Brahmi Ghrita",
    sanskrit: "\u092C\u094D\u0930\u093E\u0939\u094D\u092E\u0940 \u0918\u0943\u0924",
    type: "Ghrita",
    form: "Medicated clarified butter",
    ref: "Ashtanga Hridayam Uttarsthana 6/23-25",
    use: "Memory, intelligence, speech, epilepsy, Panchakarma",
    shelf: "16 months",
    standardBatchUnit: "L",
    rm: [
      r("Brahmi (Bacopa monnieri)", "herb", "1.536 L juice", "Whole plant juice (Swarasa)"),
      r("Cow ghee (Ghrita)", "animal", "768 ml", "Base \u2014 clarified butter"),
      r("Trikatu \u2014 Ginger", "herb", "12 g", "Rhizome"),
      r("Trikatu \u2014 Black pepper", "herb", "12 g", "Fruit"),
      r("Trikatu \u2014 Long pepper", "herb", "12 g", "Fruit"),
      r("Shankhapushpi (Clitorea ternatea)", "herb", "As per formula", "Whole plant")
    ],
    steps: stepsOf([
      "Extract fresh Brahmi Swarasa: wash, crush, press through muslin",
      "Prepare Kalka: powder all dry herbs; add water to form paste",
      "Combine: Cow ghee + Brahmi juice + Kalka paste",
      "Ratio: ghee 1 : kalka 1/4 : liquid 4",
      "Heat on medium flame; stir continuously",
      "Observe Varti/Paka Lakshana: kalka forms smooth wick, no crackling, no smoke",
      "All moisture must evaporate \u2014 Madhyama Paka endpoint",
      "Filter through multilayer muslin while hot",
      "Cool; assess organoleptic; measure specific gravity",
      "Fill in amber glass jars; seal; store cool and dry"
    ]),
    qc: qcOf(["Sp. gravity 0.900\u20130.915", "Moisture: nil", "Acid value <5.6", "Saponification value 220\u2013235", "Bacopa alkaloids \u2014 TLC/HPTLC", "Rancidity: neg"]),
    ipc: "Paka Lakshana (Varti test); Brahmi juice ratio verification; Swarasa freshness",
    dosha: "Vata-Pitta balancing; Medhya Rasayana"
  }),
  base({
    id: "ref-7",
    name: "Trikatu Churna",
    sanskrit: "\u0924\u094D\u0930\u093F\u0915\u091F\u0941 \u091A\u0942\u0930\u094D\u0923",
    type: "Churna",
    form: "Fine powder (\u226580 mesh)",
    ref: "Charaka Samhita; AFI",
    use: "Digestive fire, obesity, asthma, cough, arthritis, indigestion",
    shelf: "2 years",
    rm: [
      r("Shunthi / Dry Ginger (Zingiber officinale)", "herb", "1 part", "Dried rhizome"),
      r("Maricha / Black pepper (Piper nigrum)", "herb", "1 part", "Fruit"),
      r("Pippali / Long pepper (Piper longum)", "herb", "1 part", "Fruit")
    ],
    steps: stepsOf([
      "Procure authenticated dried ginger, black pepper, long pepper",
      "Check moisture (<12%) and pungency (organoleptic)",
      "Grind each separately in pulveriser to fine powder",
      "Sieve individually through 80-mesh; discard residue or re-grind",
      "Weigh equal quantities (1:1:1) with precision balance",
      "Blend uniformly in mixer for \u226515 minutes",
      "Check piperine content (HPLC/TLC)",
      "Fill in airtight amber glass or HDPE containers",
      "Label with manufacturing and expiry date"
    ]),
    qc: qcOf(["Moisture <8%", "Total ash <7% w/w", "Piperine NLT 0.5% w/w", "Gingerol presence \u2014 TLC", "Microbial <10\u2075 CFU/g"]),
    ipc: "Blend uniformity test; organoleptic at every batch; piperine assay",
    dosha: "Kapha-Vata reducing; Deepana-Pachana"
  }),
  base({
    id: "ref-8",
    name: "Dashamoolarishta",
    sanskrit: "\u0926\u0936\u092E\u0942\u0932\u093E\u0930\u093F\u0937\u094D\u091F",
    type: "Arishta/Asava",
    form: "Fermented decoction (alcohol 5\u201310%)",
    ref: "AFI Vol.I; Charaka Samhita",
    use: "Vata disorders, post-partum weakness, rheumatism, fever",
    shelf: "Indefinite",
    standardBatchUnit: "L",
    rm: [
      r("Bilva (Aegle marmelos)", "herb", "960 g", "Root bark"),
      r("Shyonaka (Oroxylum indicum)", "herb", "960 g", "Root"),
      r("Gambhari (Gmelina arborea)", "herb", "960 g", "Root"),
      r("Gokshura (Tribulus terrestris)", "herb", "960 g", "Root"),
      r("Jaggery (Guda)", "base", "9.6 kg", "Fermentation substrate"),
      r("Dhataki Pushpa (Woodfordia fruticosa)", "process", "480 g", "Fermentation initiator")
    ],
    steps: stepsOf([
      "Collect and authenticate all 10 Dashamoola roots",
      "Coarse-powder all roots; prepare Kasaya in 16\xD7 water; reduce to 1/4; filter",
      "Cool to 40\xB0C; transfer to fumigated fermentation vessel",
      "Dissolve jaggery; add Dhataki Pushpa; seal with 7-layer clay cloth",
      "Ferment at 25\u201330\xB0C for 30 days; check daily",
      "Candle test on day 28: flame burns brightly = complete",
      "Drain; filter through muslin (5\u03BC secondary); settle 3 days",
      "Measure alcohol (5\u201310%), pH, total solids",
      "Fill in glass bottles under N\u2082; quarantine 7 days; release on QC approval"
    ]),
    qc: qcOf(["Alcohol 5\u201310% v/v", "pH 3.5\u20134.5", "Total solids \u22655% w/v", "Clear, dark brown, no froth", "Microbial <10\u2074 CFU/ml"]),
    ipc: "Daily fermentation log; pH curve; candle test on day 15 and 28",
    dosha: "Vata-Kapha balancing"
  }),
  base({
    id: "ref-9",
    name: "Guggulu Vati (Triphala Guggulu)",
    sanskrit: "\u0924\u094D\u0930\u093F\u092B\u0932\u093E \u0917\u0941\u0917\u094D\u0917\u0941\u0932\u0941",
    type: "Vati/Gutika",
    form: "Tablet / Pill (Vati)",
    ref: "Sharangdhara Samhita; AFI",
    use: "Fistula, piles, skin diseases, Vata-Kapha disorders, obesity",
    shelf: "Indefinite",
    rm: [
      r("Triphala (Amla + Haritaki + Bibhitaki)", "herb", "Equal parts", "Fruit powder"),
      r("Shuddha Guggulu (Commiphora wightii)", "extract", "Equal to Triphala", "Purified resin"),
      r("Pippali (Piper longum)", "herb", "1 part", "Fruit"),
      r("Water / Triphala Kwatha", "base", "Sufficient", "Binding liquid")
    ],
    steps: stepsOf([
      "Shodhana of Guggulu: melt in Triphala decoction; filter; dry; repeat 3\xD7",
      "Prepare Triphala churna as per standard process",
      "Weigh Shuddha Guggulu and Triphala churna in equal proportions; add Pippali",
      "Melt Guggulu gently (40\u201350\xB0C); incorporate powders in small portions",
      "Triturate (Bhavana) until homogenous mass forms",
      "Roll into pills of 250\u2013500 mg each",
      "Dry at room temperature \u2014 prevent cracks",
      "Visual inspection: uniform shape, no cracks, glossy surface",
      "Coat lightly with beeswax if required; fill in glass containers"
    ]),
    qc: qcOf(["Weight variation <\xB15%", "Hardness 2\u20134 kg/cm\xB2", "Friability <1%", "Disintegration <30 min", "Guggulsterone \u2014 HPLC", "Microbial <10\u2075 CFU/g"]),
    ipc: "Weight uniformity check every 100 pills; Guggulu shodhana purity check",
    dosha: "Vata-Kapha reducing; anti-inflammatory"
  }),
  base({
    id: "ref-10",
    name: "Marichyadi Taila",
    sanskrit: "\u092E\u0930\u093F\u091A\u094D\u092F\u093E\u0926\u093F \u0924\u0948\u0932",
    type: "Taila",
    form: "Medicated oil (external use)",
    ref: "Charaka Samhita; AFI",
    use: "Skin diseases, psoriasis, scabies, fungal infections",
    shelf: "3 years",
    standardBatchUnit: "L",
    rm: [
      r("Maricha / Black pepper (Piper nigrum)", "herb", "As per formula", "Fruit"),
      r("Nimba / Neem (Azadirachta indica)", "herb", "As per formula", "Leaf / bark"),
      r("Haridra (Curcuma longa)", "herb", "As per formula", "Rhizome"),
      r("Sesame oil (Til Taila)", "base", "Base oil", "Cold-pressed")
    ],
    steps: stepsOf([
      "Prepare Kasaya from herbs + water (16\xD7 ratio); reduce to 1/4; filter",
      "Prepare Kalka (fine paste) from key herbs",
      "Combine sesame oil + kasaya + kalka in SS vessel",
      "Heat on medium flame, stir continuously until water evaporates",
      "Perform Varti test to confirm Taila Paka endpoint",
      "Filter through multilayer muslin while hot",
      "Cool and assess clarity, aroma, colour",
      "Fill in amber glass bottles; label for external use only"
    ]),
    qc: qcOf(["Sp. gravity 0.900\u20130.920", "Acid value <5", "Rancidity: neg", "Colour: dark yellow to brown", "Iodine value 103\u2013112", "Moisture: nil"]),
    ipc: "Paka Lakshana; Varti test; aroma check",
    dosha: "Kapha-Pitta balancing"
  }),
  base({
    id: "ref-11",
    name: "Abhraka Bhasma",
    sanskrit: "\u0905\u092D\u094D\u0930\u0915 \u092D\u0938\u094D\u092E",
    type: "Bhasma",
    form: "Ultra-fine calcined mineral (Rasausadhi)",
    ref: "Rasa Tarangini; AFI Vol.III",
    use: "Respiratory diseases, diabetes, anemia, cardiac weakness, Rasayana",
    shelf: "Indefinite",
    rm: [
      r("Abhraka (Mica / Biotite) \u2014 Shuddha", "mineral", "Per batch", "Purified mica flakes"),
      r("Triphala Kwatha", "herb", "For Shodhana", "Decoction"),
      r("Kumari swarasa (Aloe vera juice)", "herb", "For Bhavana", "Fresh leaf juice"),
      r("Cow dung cakes (Gobar Upla)", "animal", "For Puta", "For Gajaputa firing"),
      r("Cow ghee (Ghrita)", "animal", "For quenching", "Used in Nirvapana")
    ],
    steps: stepsOf([
      "Shodhana: heat mica to red-hot; quench in Triphala decoction 7\u201321 times",
      "Dry purified mica flakes completely",
      "Bhavana: triturate mica in Aloe vera juice for 12 hours; form thin cakes; dry",
      "Marana: place cakes in Sharava (crucible); seal; fire in Gajaputa",
      "Cool fully before opening (minimum 12 hours)",
      "Check colour (grey-black); collect powder",
      "Repeat Bhavana + Marana for 7\u2013100 puta cycles",
      "Final QC: Bhasma Pariksha tests",
      "Store in airtight glass container away from moisture"
    ]),
    qc: qcOf(["Rekhapurnata (fills finger lines)", "Varitaratwa (floats on water)", "Apunarbhava (no reversion)", "Nishchandratwa (no metallic sheen)", "XRF: Mg/Fe/Al profile", "Heavy metals: As <3ppm, Pb <10ppm", "Particle size <1\u03BCm"]),
    ipc: "Puta cycle count documentation; colour/texture check after each cycle; Bhasma Pariksha at final stage",
    dosha: "Tridoshic; respiratory affinity"
  }),
  base({
    id: "ref-12",
    name: "Kumaryasava",
    sanskrit: "\u0915\u0941\u092E\u093E\u0930\u094D\u092F\u093E\u0938\u0935",
    type: "Arishta/Asava",
    form: "Fermented herbal liquid (Asava)",
    ref: "AFI Vol.I; Bhaishajya Ratnavali",
    use: "Liver disorders, digestive weakness, jaundice, anemia",
    shelf: "Indefinite",
    standardBatchUnit: "L",
    rm: [
      r("Kumari / Aloe vera (Aloe barbadensis)", "herb", "Fresh juice \u2014 main", "Fresh leaf juice"),
      r("Jaggery (Guda)", "base", "Per formula", "Fermentation substrate"),
      r("Dhataki Pushpa (Woodfordia fruticosa)", "process", "Standard qty", "Fermentation initiator"),
      r("Haritaki (Terminalia chebula)", "herb", "As per formula", "Fruit"),
      r("Amalaki (Emblica officinalis)", "herb", "As per formula", "Fruit"),
      r("Trikatu (Ginger, Pepper, Long pepper)", "herb", "As per formula", "Mixed")
    ],
    steps: stepsOf([
      "Extract fresh Kumari Swarasa: wash, peel, express gel+juice; filter",
      "Transfer to fumigated fermentation vessel",
      "Add jaggery, Dhataki Pushpa, herb powders",
      "Seal vessel with 7-layer clay cloth",
      "Ferment at 25\u201330\xB0C for 30 days; monitor daily",
      "Test completion: clear, aromatic, candle test positive",
      "Drain and filter through muslin and 5\u03BC filter",
      "Measure alcohol (5\u201310%), pH 3.5\u20134.5, total solids",
      "Settle 3 days; fill in glass bottles under nitrogen; QC release"
    ]),
    qc: qcOf(["Alcohol 5\u201310% v/v", "pH 3.5\u20134.5", "Clear brownish-yellow liquid", "Aloin NLT 1% (HPTLC)", "Total solids \u22654% w/v", "Microbial <10\u2074 CFU/ml"]),
    ipc: "Swarasa freshness (use within 4 hours); daily fermentation log",
    dosha: "Pitta-Kapha balancing; liver tonic"
  })
];

// src/lib/formulationConstants.ts
var CAT_LABELS = {
  herb: "Herbs",
  extract: "Extracts",
  mineral: "Metals & Minerals",
  animal: "Animal by-products",
  base: "Bases & Excipients",
  process: "Process agents"
};
var DOSAGE_FORMS = ["All", "Churna", "Arishta/Asava", "Avaleha", "Taila", "Ghrita", "Vati/Gutika", "Bhasma"];

// src/lib/mcp/data.ts
function summarise(f) {
  return {
    id: f.id,
    name: f.name,
    sanskrit: f.sanskrit,
    type: f.type,
    dosageForm: f.form,
    pharmacopoeialReference: f.ref,
    therapeuticUse: f.use,
    shelfLife: f.shelf,
    standardBatchSize: `${f.standardBatchSize} ${f.standardBatchUnit}`,
    ingredientCount: f.rm.length
  };
}
function detail(f) {
  return {
    ...summarise(f),
    dosha: f.dosha,
    expectedYieldPct: f.expectedYieldPct,
    ingredients: f.rm.map((rm) => ({
      name: rm.name,
      category: rm.cat,
      categoryLabel: CAT_LABELS[rm.cat] ?? rm.cat,
      quantity: rm.qty > 0 ? `${rm.qty} ${rm.unit}` : rm.unit,
      partUsed: rm.part,
      botanical: rm.botanical
    })),
    subProcesses: (f.subProcesses ?? []).map((sp) => ({
      type: sp.type,
      name: sp.name,
      description: sp.description,
      waterRatio: sp.waterRatio,
      reductionTarget: sp.reductionTarget,
      cycles: sp.numberOfCycles,
      completionTest: sp.completionTest,
      ingredients: sp.ingredients.map((i) => i.name)
    })),
    processSteps: f.steps.map((s, i) => ({
      no: i + 1,
      step: s.step,
      equipment: s.equipment,
      duration: s.duration,
      temperature: s.temp,
      ipcCheck: s.ipcCheck
    })),
    qcParameters: f.qc.map((q) => ({ parameter: q.parameter, specification: q.spec })),
    inProcessControls: f.ipc,
    packaging: {
      packSizes: f.packaging?.packSizes ?? [],
      qcRetainSample: f.packaging?.qcRetainSample
    }
  };
}
function findFormulation(query) {
  const q = query.trim().toLowerCase();
  return referenceFormulations.find((f) => f.id.toLowerCase() === q) ?? referenceFormulations.find((f) => f.name.toLowerCase() === q) ?? referenceFormulations.find(
    (f) => f.name.toLowerCase().includes(q) || f.sanskrit.includes(query.trim())
  );
}

// src/lib/mcp/tools/list-formulations.ts
var list_formulations_default = defineTool({
  name: "list_formulations",
  title: "List reference formulations",
  description: "List the built-in Ayurvedic reference formulations (Master Formula Records) available in AyurMap Studio, optionally filtered by dosage form or a text query.",
  inputSchema: {
    dosageForm: z.string().optional().describe('Filter by dosage form, e.g. "Churna", "Taila", "Bhasma". Omit or "All" for every form.'),
    query: z.string().optional().describe("Free-text match on name, Sanskrit name or therapeutic use.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ dosageForm, query }) => {
    let rows = referenceFormulations;
    if (dosageForm && dosageForm.toLowerCase() !== "all") {
      const d = dosageForm.toLowerCase();
      rows = rows.filter((f) => f.type.toLowerCase().includes(d) || f.form.toLowerCase().includes(d));
    }
    if (query) {
      const q = query.toLowerCase();
      rows = rows.filter(
        (f) => f.name.toLowerCase().includes(q) || f.sanskrit.includes(query) || f.use.toLowerCase().includes(q)
      );
    }
    const results = rows.map(summarise);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, formulations: results }
    };
  }
});

// src/lib/mcp/tools/get-formulation.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_formulation_default = defineTool2({
  name: "get_formulation",
  title: "Get formulation record",
  description: "Get the full reference Master Formula Record for one Ayurvedic formulation: ingredients with parts used, sub-processes (Kwatha/Kalka/Bhavana/Shodhana), process steps, QC parameters and packaging.",
  inputSchema: {
    formulation: z2.string().min(1).describe('Formulation id or name, e.g. "Triphala Churna" or "ref-1".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ formulation }) => {
    const found = findFormulation(formulation);
    if (!found) throw new ToolError(`No reference formulation matches "${formulation}".`);
    const record = detail(found);
    return {
      content: [{ type: "text", text: JSON.stringify(record, null, 2) }],
      structuredContent: { formulation: record }
    };
  }
});

// src/lib/mcp/tools/find-formulations-by-ingredient.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var find_formulations_by_ingredient_default = defineTool3({
  name: "find_formulations_by_ingredient",
  title: "Find formulations by ingredient",
  description: "Find which reference Ayurvedic formulations use a given raw material (dravya), matching on common or botanical name. Useful for traceability and substitution questions.",
  inputSchema: {
    ingredient: z3.string().min(2).describe('Raw material name or part of it, e.g. "Haritaki", "Terminalia", "Guduchi".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ ingredient }) => {
    const q = ingredient.trim().toLowerCase();
    const matches = referenceFormulations.map((f) => {
      const hits = [
        ...f.rm,
        ...(f.subProcesses ?? []).flatMap((sp) => sp.ingredients)
      ].filter(
        (rm) => rm.name.toLowerCase().includes(q) || (rm.botanical ?? "").toLowerCase().includes(q)
      );
      return { f, hits };
    }).filter((m) => m.hits.length > 0).map(({ f, hits }) => ({
      id: f.id,
      name: f.name,
      type: f.type,
      pharmacopoeialReference: f.ref,
      matchedIngredients: hits.map((rm) => ({
        name: rm.name,
        category: rm.cat,
        categoryLabel: CAT_LABELS[rm.cat] ?? rm.cat,
        quantity: rm.qty > 0 ? `${rm.qty} ${rm.unit}` : rm.unit,
        partUsed: rm.part
      }))
    }));
    return {
      content: [
        {
          type: "text",
          text: matches.length === 0 ? `No reference formulation uses an ingredient matching "${ingredient}".` : JSON.stringify(matches, null, 2)
        }
      ],
      structuredContent: { count: matches.length, formulations: matches }
    };
  }
});

// src/lib/mcp/tools/get-compliance-reference.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var SCHEDULE_TA_CATEGORIES = [
  { key: "herb", scheduleTaGroup: "Herbs (Kasthausadhi)", note: "Plant-origin dravyas; recorded with part used and supplier source." },
  { key: "extract", scheduleTaGroup: "Herbs (Kasthausadhi)", note: "Standardised plant extracts; recorded with marker assay." },
  { key: "mineral", scheduleTaGroup: "Metals & Minerals (Rasausadhi)", note: "Requires Shodhana purification records before use." },
  { key: "animal", scheduleTaGroup: "Animal by-products", note: "Requires source declaration and traceability." },
  { key: "base", scheduleTaGroup: "Bases & Excipients", note: "Oils, ghrita, sugars, honey and other vehicles." },
  { key: "process", scheduleTaGroup: "Process agents", note: "Fermentation and processing aids; not part of final label claim." }
];
var SUB_PROCESS_TYPES = [
  { type: "Kwatha", meaning: "Decoction \u2014 herbs boiled with water and reduced to a target fraction." },
  { type: "Kalka", meaning: "Wet paste of fresh or soaked dravyas used as an intermediate." },
  { type: "Bhavana", meaning: "Repeated levigation/trituration cycles with a liquid medium." },
  { type: "Shodhana", meaning: "Purification of metals/minerals through defined cycles before use." },
  { type: "Other", meaning: "Any other named intermediate preparation." }
];
var get_compliance_reference_default = defineTool4({
  name: "get_compliance_reference",
  title: "Get compliance reference",
  description: "Return AyurMap Studio's compliance reference metadata: raw material categories and their Schedule TA reporting groups, dosage forms, and Ayurvedic sub-process (intermediate preparation) types.",
  inputSchema: {
    section: z4.enum(["all", "categories", "dosageForms", "subProcesses"]).optional().describe('Which section to return. Defaults to "all".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ section }) => {
    const which = section ?? "all";
    const payload = {};
    if (which === "all" || which === "categories") {
      payload.rawMaterialCategories = SCHEDULE_TA_CATEGORIES.map((c) => ({
        ...c,
        label: CAT_LABELS[c.key] ?? c.key
      }));
    }
    if (which === "all" || which === "dosageForms") {
      payload.dosageForms = DOSAGE_FORMS.filter((d) => d !== "All");
    }
    if (which === "all" || which === "subProcesses") {
      payload.subProcessTypes = SUB_PROCESS_TYPES;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ayurmap-studio",
  title: "AyurMap Studio",
  version: "0.1.0",
  instructions: "Reference tools for AyurMap Studio, an Ayurvedic production management app. Use `list_formulations` to browse the built-in Master Formula Records, `get_formulation` for a full record (ingredients, sub-processes, process steps, QC parameters, packaging), `find_formulations_by_ingredient` for traceability questions about a dravya, and `get_compliance_reference` for raw-material categories, Schedule TA groups, dosage forms and sub-process types. These tools expose public reference data only \u2014 batch, stock and GRN records live in each user's browser and are not available here.",
  tools: [list_formulations_default, get_formulation_default, find_formulations_by_ingredient_default, get_compliance_reference_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
